services:
  mydb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - destro
    volumes:
      - ./data:/data/db
    healthcheck:
      test: ['CMD', 'mongo', '--eval', 'db.stats()']
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    depends_on:
      - mydb
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: package.json
    restart: always

    networks:
      - destro
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: ['npm', 'run', 'dev']
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

        - action: rebuild
          path: package.json

    networks:
      - destro

  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - '8080:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/nginx.conf
    networks:
      - destro

networks:
  destro:
    driver: bridge

volumes:
  destro:
