services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
        - "3000:3000"
    command: ["npm", "run" , "dev"]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

        - action: rebuild
          path: package.json