services:
  mydb:
    image: mongo
    restart: always
    networks:
      - destro
    volumes:
      - ./data:/data/db
    healthcheck:
      test: ['CMD', 'mongo', '--eval', 'db.stats()']
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - mydb
    restart: always

    networks:
      - destro
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - destro

  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - '8080:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/nginx.conf
    networks:
      - destro

networks:
  destro:
    driver: bridge

volumes:
  destro:
