services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
        - "3000:3000"
    command: ["npm", "run" , "dev"]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

        - action: rebuild
          path: package.json
    networks:
      - destro

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - frontend  
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/nginx.conf
    networks:
      - destro

networks:
  destro:
    driver: bridge

volumes:
  destro: