services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
  
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

        - action: rebuild
          path: package.json
    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 5
      
    networks:
      - destro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: ["npm", "run" , "dev"]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

        - action: rebuild
          path: package.json
 
    networks:
      - destro

  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
        backend:
          condition: service_healthy 
        frontend:
          condition: service_completed_successfully
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/nginx.conf
    networks:
      - destro

networks:
  destro:
    driver: bridge

volumes:
  destro: